In [ ]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

import warnings
warnings.filterwarnings("ignore")
#Please ignore the warnings with version change

from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
trainfile = r'/gdrive/My Drive/Insurance Fraud - TRAIN-3000.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/Insurance Fraud -TEST-12900.csv'
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)


(2999, 32)
(12918, 32)


In [ ]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 2999 non-null   object
 1   WEEKOFMONTH           2999 non-null   int64 
 2   DAYOFWEEK             2999 non-null   object
 3   MAKE                  2999 non-null   object
 4   ACCIDENTAREA          2999 non-null   object
 5   DAYOFWEEKCLAIMED      2999 non-null   object
 6   MONTHCLAIMED          2999 non-null   object
 7   WEEKOFMONTHCLAIMED    2999 non-null   int64 
 8   SEX                   2999 non-null   object
 9   MARITALSTATUS         2999 non-null   object
 10  AGE                   2999 non-null   int64 
 11  FAULT                 2999 non-null   object
 12  POLICYTYPE            2999 non-null   object
 13  VEHICLECATEGORY       2999 non-null   object
 14  VEHICLEPRICE          2999 non-null   object
 15  REPNUMBER             2999 non-null   

In [ ]:
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12918 entries, 0 to 12917
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 12918 non-null  object
 1   WEEKOFMONTH           12918 non-null  int64 
 2   DAYOFWEEK             12918 non-null  object
 3   MAKE                  12918 non-null  object
 4   ACCIDENTAREA          12918 non-null  object
 5   DAYOFWEEKCLAIMED      12918 non-null  object
 6   MONTHCLAIMED          12918 non-null  object
 7   WEEKOFMONTHCLAIMED    12918 non-null  int64 
 8   SEX                   12918 non-null  object
 9   MARITALSTATUS         12918 non-null  object
 10  AGE                   12918 non-null  int64 
 11  FAULT                 12918 non-null  object
 12  POLICYTYPE            12918 non-null  object
 13  VEHICLECATEGORY       12918 non-null  object
 14  VEHICLEPRICE          12918 non-null  object
 15  REPNUMBER             12918 non-null

In [ ]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'FRAUDFOUND']
['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'F

In [ ]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['FRAUDFOUND']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['FRAUDFOUND']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(2999, 31)
(2999, 1)
Test Set shape:
(12918, 31)
(12918, 1)


In [ ]:
#List of Categorical Features
#List of Categorical Features
categoricalFeatures = ['MONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'SEX', 'MARITALSTATUS','FAULT','POLICYTYPE','VEHICLECATEGORY','VEHICLEPRICE','DAYS_POLICY_ACCIDENT','DAYS_POLICY_CLAIM','PASTNUMBEROFCLAIMS','AGEOFVEHICLE','AGEOFPOLICYHOLDER','POLICEREPORTFILED','WITNESSPRESENT','AGENTTYPE','NUMBEROFSUPPLIMENTS','ADDRESSCHANGE_CLAIM','NUMBEROFCARS','BASEPOLICY']

In [ ]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]),columns=ohe.get_feature_names_out(),index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
267             4                   4   60         10         400   
1733            3                   3   41          1         400   
1159            2                   2   30         14         400   
962             4                   4   28         12         400   
2290            1                   1   75         12         400   

      DRIVERRATING  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  ...  \
267              4  1995        0.0        0.0        0.0  ...   
1733             3  1995        0.0        0.0        0.0  ...   
1159             2  1994        0.0        0.0        0.0  ...   
962              2  1995        0.0        0.0        0.0  ...   
2290             4  1995        1.0        0.0        0.0  ...   

      ADDRESSCHANGE_CLAIM_4_to_8_years  ADDRESSCHANGE_CLAIM_no_change  \
267                                0.0                            1.0   
1733                               0.0                            1.0   
1159                               0.0                            1.0   
962                                0.0                            1.0   
2290                               0.0                            1.0   

      ADDRESSCHANGE_CLAIM_under_6_months  NUMBEROFCARS_1-vehicle  \
267                                  0.0                     1.0   
1733                                 0.0                     1.0   
1159                                 0.0                     1.0   
962                                  0.0                     1.0   
2290                                 0.0                     1.0   

      NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  NUMBEROFCARS_5_to_8  \
267                       0.0                  0.0                  0.0   
1733                      0.0                  0.0                  0.0   
1159                      0.0                  0.0                  0.0   
962                       0.0                  0.0                  0.0   
2290                      0.0                  0.0                  0.0   

      BASEPOLICY_All_Perils  BASEPOLICY_Collision  BASEPOLICY_Liability  
267                     0.0                   1.0                   0.0  
1733                    0.0                   1.0                   0.0  
1159                    0.0                   1.0                   0.0  
962                     1.0                   0.0                   0.0  
2290                    0.0                   1.0                   0.0  

[5 rows x 139 columns]

In [ ]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names_out(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
9969             5                   2   45         10         400   
2189             3                   4   29         10         400   
4642             1                   1   31          1         400   
11978            2                   3   45         14         400   
4283             3                   3   38          6         400   

       DRIVERRATING  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  ...  \
9969              2  1995        0.0        0.0        0.0  ...   
2189              4  1995        0.0        0.0        0.0  ...   
4642              1  1994        0.0        0.0        0.0  ...   
11978             1  1994        0.0        0.0        0.0  ...   
4283              3  1996        0.0        1.0        0.0  ...   

       ADDRESSCHANGE_CLAIM_4_to_8_years  ADDRESSCHANGE_CLAIM_no_change  \
9969                                0.0                            1.0   
2189                                0.0                            1.0   
4642                                0.0                            1.0   
11978                               0.0                            1.0   
4283                                0.0                            1.0   

       ADDRESSCHANGE_CLAIM_under_6_months  NUMBEROFCARS_1-vehicle  \
9969                                  0.0                     1.0   
2189                                  0.0                     1.0   
4642                                  0.0                     1.0   
11978                                 0.0                     1.0   
4283                                  0.0                     1.0   

       NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  NUMBEROFCARS_5_to_8  \
9969                       0.0                  0.0                  0.0   
2189                       0.0                  0.0                  0.0   
4642                       0.0                  0.0                  0.0   
11978                      0.0                  0.0                  0.0   
4283                       0.0                  0.0                  0.0   

       BASEPOLICY_All_Perils  BASEPOLICY_Collision  BASEPOLICY_Liability  
9969                     1.0                   0.0                   0.0  
2189                     0.0                   1.0                   0.0  
4642                     0.0                   1.0                   0.0  
11978                    1.0                   0.0                   0.0  
4283                     1.0                   0.0                   0.0  

[5 rows x 139 columns]

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

In [ ]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier()

In [ ]:
X_Pred = dt.predict(Xtest)
XPred = dt.predict(Xtrain)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred))
print("Max Depth",dt.get_depth())
print("Leaf",dt.get_n_leaves())
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred))
print ("Variable Rankings",dt.feature_importances_)

Train Accuracy: 1.0
Test Accuracy: 0.8831088403777675
Confusion Matrix for Decision Tree:
[[10962  1458]
 [   52   446]]
Max Depth 23
Leaf 288
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       1.00      0.88      0.94     12420
         Yes       0.23      0.90      0.37       498

    accuracy                           0.88     12918
   macro avg       0.61      0.89      0.65     12918
weighted avg       0.97      0.88      0.91     12918

Variable Rankings [0.03758662 0.01487617 0.06687136 0.05840002 0.00025712 0.02491899
 0.11206823 0.00017719 0.0044922  0.00227181 0.00893391 0.00260823
 0.00588378 0.00261424 0.00548228 0.00473487 0.0110194  0.00715204
 0.01071247 0.00360197 0.00856278 0.01615641 0.00997957 0.0092918
 0.00990903 0.00471489 0.00673436 0.00200181 0.00783382 0.
 0.00264341 0.00264997 0.02300618 0.         0.         0.
 0.0203089  0.         0.00257633 0.         0.00399436 0.
 0.00127667 0

In [ ]:
X_Pred1 = rf.predict(Xtest)
XPred1 = rf.predict(Xtrain)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred1))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred1))
print ("Variable Rankings",dt.feature_importances_)

Train Accuracy: 1.0
Test Accuracy: 0.966171233937142
Confusion Matrix for Decision Tree:
[[12062   358]
 [   79   419]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.99      0.97      0.98     12420
         Yes       0.54      0.84      0.66       498

    accuracy                           0.97     12918
   macro avg       0.77      0.91      0.82     12918
weighted avg       0.98      0.97      0.97     12918

Variable Rankings [0.03758662 0.01487617 0.06687136 0.05840002 0.00025712 0.02491899
 0.11206823 0.00017719 0.0044922  0.00227181 0.00893391 0.00260823
 0.00588378 0.00261424 0.00548228 0.00473487 0.0110194  0.00715204
 0.01071247 0.00360197 0.00856278 0.01615641 0.00997957 0.0092918
 0.00990903 0.00471489 0.00673436 0.00200181 0.00783382 0.
 0.00264341 0.00264997 0.02300618 0.         0.         0.
 0.0203089  0.         0.00257633 0.         0.00399436 0.
 0.00127667 0.00616721 0.01248296 0.

**Decision Tree - Random Search Parameter Changes **

In [ ]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(15,700,10),'max_depth':
            range(10,20,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=20)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 215, 'max_depth': 12, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.783016
--- 20.87701940536499 seconds ---


In [ ]:
import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,700,10),'max_depth':
            range(10,30,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=10)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 90, 'max_depth': 28, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.882877
--- 7.766108512878418 seconds ---


In [ ]:
import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,200,10),'max_depth':
            range(15,20,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=8)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

**Decision Tree - Grid search parameter changes**

In [ ]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree - Metric 1")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Metric 1
{'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 50}
accuracy Score for Decision Tree:0.884115
--- 211.30279421806335 seconds ---


In [ ]:
import time
start_time = time.time()

print("GridSearchCV-Decision tree - Metric 2")
grid_parameters1={'min_samples_leaf' : range(10,250,10),'max_depth':
            range(5,15,2),'criterion':['gini','entropy']}
dt_grid1 = GridSearchCV(dt,grid_parameters1)
dt_grid1.fit(Xtrain, Ytrain)
grid_parm1=dt_grid1.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid1.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Metric 2
{'criterion': 'entropy', 'max_depth': 7, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.897430
--- 34.41148090362549 seconds ---


In [ ]:
start_time = time.time()

print("GridSearchCV-Decision tree - Parameter 2")
grid_parameters2={'min_samples_leaf' : range(10,500,20),'max_depth':
            range(10,20,2),'criterion':['gini','entropy']}
dt_grid2 = GridSearchCV(dt,grid_parameters2)
dt_grid2.fit(Xtrain, Ytrain)
grid_parm2=dt_grid2.best_params_
print(grid_parm2)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid2.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Parameter 2
{'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 50}
accuracy Score for Decision Tree:0.884115
--- 34.50017237663269 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [ ]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8828766062858028
Confusion Matrix for Decision Tree:
[[11270  1150]
 [  363   135]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.91      0.94     12420
         Yes       0.11      0.27      0.15       498

    accuracy                           0.88     12918
   macro avg       0.54      0.59      0.54     12918
weighted avg       0.94      0.88      0.91     12918

[0.90865385 0.79615385 0.55       0.5        0.55696203]


In [ ]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')

Test Accuracy: 0.8974299427155906
Confusion Matrix for Decision Tree:
[[11427   993]
 [  332   166]]
Printing the precision and recall, among other metrics


In [ ]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth':
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 40, 'min_samples_leaf': 30, 'max_features': 30, 'max_depth': 5}
accuracy Score for Decision Tree:0.929246
--- 13.131935834884644 seconds ---


In [ ]:
# GRID SEARCH .............
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(Xtrain, Ytrain)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Random Forest
{'max_depth': 9, 'max_features': 30, 'min_samples_leaf': 30, 'n_estimators': 30}
accuracy Score for Decision Tree:0.928007
--- 221.93581533432007 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

In [ ]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
clf_cv_score = cross_val_score(rfRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

In [ ]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))

Test Accuracy: 0.9272333178510606
Confusion Matrix for Decision Tree:
[[11859   561]
 [  379   119]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.95      0.96     12420
         Yes       0.17      0.24      0.20       498

    accuracy                           0.93     12918
   macro avg       0.57      0.60      0.58     12918
weighted avg       0.94      0.93      0.93     12918

