In [ ]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

import warnings
warnings.filterwarnings("ignore")
#Please ignore the warnings with version change

from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
trainfile = r'/gdrive/My Drive/Portugese Bank Data - TRAIN.csv'
trainData = pd.read_csv(trainfile) #creates a dataframe
testfile = r'/gdrive/My Drive/Portugese Bank Data - TEST.csv'
testData = pd.read_csv(testfile)  #creates a dataframe


print(trainData.shape)
print(testData.shape)

(4521, 17)
(45211, 17)


In [ ]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


In [ ]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']


In [ ]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['y']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['y']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(4521, 16)
(4521, 1)
Test Set shape:
(45211, 16)
(45211, 1)


In [ ]:
#List of Categorical Features
categoricalFeatures = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month','poutcome']


In [ ]:
# OneHotEncoding on Train (fit & transform)
# OneHotEncoding is to be done on Categorical variables.
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]),columns=ohe.get_feature_names_out(),index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
1006   40        5   18       219         3     -1         0         0.0   
1011   42      198    8       314         1     -1         0         0.0   
881    31      102   17       460         2    345         2         0.0   
3872   29      209   28       487         7     -1         0         0.0   
269    56     1007   29        88         6     -1         0         0.0   

      job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  month_may  \
1006              0.0               0.0  ...        0.0        0.0        0.0   
1011              0.0               1.0  ...        0.0        0.0        1.0   
881               0.0               0.0  ...        0.0        0.0        0.0   
3872              0.0               0.0  ...        0.0        0.0        0.0   
269               0.0               0.0  ...        0.0        0.0        0.0   

      month_nov  month_oct  month_sep  poutcome_failure  poutcome_other  \
1006        1.0        0.0        0.0               0.0             0.0   
1011        0.0        0.0        0.0               0.0             0.0   
881         0.0        0.0        0.0               1.0             0.0   
3872        0.0        0.0        0.0               0.0             0.0   
269         0.0        0.0        0.0               0.0             0.0   

      poutcome_success  poutcome_unknown  
1006               0.0               1.0  
1011               0.0               1.0  
881                0.0               0.0  
3872               0.0               1.0  
269                0.0               1.0  

[5 rows x 51 columns]

In [ ]:
print(Xtrain.columns)

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown'],
      dtype='object')


In [ ]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]),columns=ohe.get_feature_names_out(),index=Xtest.index)
Xtest = pd.concat([Xtest,Xcat],axis=1)
Xtest.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtest.sample(5)

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
31179   34     -398   27        47         8     -1         0         0.0   
26066   35      951   19       220         2     -1         0         0.0   
3612    46     8717   15       343         5     -1         0         0.0   
24701   56     1092   17       176         3    186         4         0.0   
9417    35     8127    6       315         1     -1         0         0.0   

       job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
31179              1.0               0.0  ...        0.0        0.0   
26066              0.0               0.0  ...        0.0        0.0   
3612               0.0               0.0  ...        0.0        0.0   
24701              0.0               0.0  ...        0.0        0.0   
9417               0.0               0.0  ...        1.0        0.0   

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
31179        0.0        0.0        0.0        0.0               0.0   
26066        0.0        1.0        0.0        0.0               0.0   
3612         1.0        0.0        0.0        0.0               0.0   
24701        0.0        1.0        0.0        0.0               1.0   
9417         0.0        0.0        0.0        0.0               0.0   

       poutcome_other  poutcome_success  poutcome_unknown  
31179             0.0               0.0               1.0  
26066             0.0               0.0               1.0  
3612              0.0               0.0               1.0  
24701             0.0               0.0               0.0  
9417              0.0               0.0               1.0  

[5 rows x 51 columns]

In [ ]:
print(Xtest.columns)

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'education_primary', 'education_secondary', 'education_tertiary',
       'education_unknown', 'default_no', 'default_yes', 'housing_no',
       'housing_yes', 'loan_no', 'loan_yes', 'contact_cellular',
       'contact_telephone', 'contact_unknown', 'month_apr', 'month_aug',
       'month_dec', 'month_feb', 'month_jan', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown'],
      dtype='object')


In [ ]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

In [ ]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

RandomForestClassifier()

In [ ]:
X_Pred = dt.predict(Xtest)
XPred = dt.predict(Xtrain)
#Model Accuracy (Decision Tree)
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred))
print("Max Depth",dt.get_depth())
print("Leaf",dt.get_n_leaves())
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred))
print ("Variable Rankings",dt.feature_importances_)

Train Accuracy: 1.0
Test Accuracy: 0.8809139368737696
Confusion Matrix for Decision Tree:
[[37088  2834]
 [ 2550  2739]]
Max Depth 28
Leaf 378
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.94      0.93      0.93     39922
         yes       0.49      0.52      0.50      5289

    accuracy                           0.88     45211
   macro avg       0.71      0.72      0.72     45211
weighted avg       0.88      0.88      0.88     45211

Variable Rankings [0.08553847 0.08708254 0.10858606 0.25670638 0.03175679 0.04690072
 0.01089615 0.0019076  0.00633917 0.00184891 0.00282642 0.0085657
 0.01096978 0.00044586 0.00299378 0.00673543 0.01695518 0.00225256
 0.00177167 0.00817401 0.00852663 0.00181785 0.         0.01196778
 0.01948057 0.0022527  0.0074061  0.00040245 0.00977029 0.00990805
 0.00514524 0.00253095 0.01003746 0.00493385 0.01208128 0.00862086
 0.00896793 0.         0.01223353 0.         0.0063439  

In [ ]:
X_Pred1 = rf.predict(Xtest)
XPred1 = rf.predict(Xtrain)
#Model Accuracy (Random Forest)
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred1))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred1))
print ("Variable Rankings",dt.feature_importances_)

Train Accuracy: 0.9995576199955762
Test Accuracy: 0.9110614673420185
Confusion Matrix for Decision Tree:
[[39265   657]
 [ 3364  1925]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.98      0.95     39922
         yes       0.75      0.36      0.49      5289

    accuracy                           0.91     45211
   macro avg       0.83      0.67      0.72     45211
weighted avg       0.90      0.91      0.90     45211

Variable Rankings [0.08553847 0.08708254 0.10858606 0.25670638 0.03175679 0.04690072
 0.01089615 0.0019076  0.00633917 0.00184891 0.00282642 0.0085657
 0.01096978 0.00044586 0.00299378 0.00673543 0.01695518 0.00225256
 0.00177167 0.00817401 0.00852663 0.00181785 0.         0.01196778
 0.01948057 0.0022527  0.0074061  0.00040245 0.00977029 0.00990805
 0.00514524 0.00253095 0.01003746 0.00493385 0.01208128 0.00862086
 0.00896793 0.         0.01223353 0.         0.0063439  0.01774

**Decision Tree - Random Search Parameter Changes **

In [ ]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(15,700,10),'max_depth':
            range(10,20,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=20)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 25, 'max_depth': 10, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.898741
--- 22.116533517837524 seconds ---


In [ ]:
import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,700,10),'max_depth':
            range(10,30,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=10)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 60, 'max_depth': 16, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.897746
--- 8.353017568588257 seconds ---


In [ ]:
import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,200,10),'max_depth':
            range(15,20,2),'criterion':['gini','entropy']}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=8)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 20, 'max_depth': 19, 'criterion': 'gini'}
accuracy Score for Decision Tree:0.896839
--- 10.912633657455444 seconds ---


**Decision Tree - Grid search parameter changes**

In [ ]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree - Metric 1")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Metric 1
{'criterion': 'gini', 'max_depth': 15, 'min_samples_leaf': 60}
accuracy Score for Decision Tree:0.896596
--- 21.510132789611816 seconds ---


In [ ]:
import time
start_time = time.time()

print("GridSearchCV-Decision tree - Metric 2")
grid_parameters1={'min_samples_leaf' : range(10,250,10),'max_depth':
            range(5,15,2),'criterion':['gini','entropy']}
dt_grid1 = GridSearchCV(dt,grid_parameters1)
dt_grid1.fit(Xtrain, Ytrain)
grid_parm1=dt_grid1.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid1.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Metric 2
{'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.896220
--- 50.99293327331543 seconds ---


In [ ]:
start_time = time.time()

print("GridSearchCV-Decision tree - Parameter 2")
grid_parameters2={'min_samples_leaf' : range(10,500,20),'max_depth':
            range(10,20,2),'criterion':['gini','entropy']}
dt_grid2 = GridSearchCV(dt,grid_parameters2)
dt_grid2.fit(Xtrain, Ytrain)
grid_parm2=dt_grid2.best_params_
print(grid_parm2)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid2.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree - Parameter 2
{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 50}
accuracy Score for Decision Tree:0.895026
--- 36.94597339630127 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [ ]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.896839264780695
Confusion Matrix for Decision Tree:
[[38656  1266]
 [ 3398  1891]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.97      0.94     39922
         yes       0.60      0.36      0.45      5289

    accuracy                           0.90     45211
   macro avg       0.76      0.66      0.70     45211
weighted avg       0.88      0.90      0.89     45211

[0.64315476 0.62567308 0.64072115 0.64908654 0.65514423]


In [ ]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')

Test Accuracy: 0.8962199464732035
Confusion Matrix for Decision Tree:
[[38959   963]
 [ 3729  1560]]
Printing the precision and recall, among other metrics


In [ ]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth':
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 30, 'min_samples_leaf': 30, 'max_features': 30, 'max_depth': 5}
accuracy Score for Decision Tree:0.900798
--- 35.52417778968811 seconds ---


In [ ]:
# GRID SEARCH .............
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(Xtrain, Ytrain)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Random Forest
{'max_depth': 9, 'max_features': 30, 'min_samples_leaf': 20, 'n_estimators': 20}
accuracy Score for Decision Tree:0.900931
--- 354.72748732566833 seconds ---


In [ ]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

In [ ]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
clf_cv_score = cross_val_score(rfRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8998031452522616
Confusion Matrix for Decision Tree:
[[38819  1103]
 [ 3427  1862]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.97      0.94     39922
         yes       0.63      0.35      0.45      5289

    accuracy                           0.90     45211
   macro avg       0.77      0.66      0.70     45211
weighted avg       0.88      0.90      0.89     45211

[0.65705357 0.64302885 0.63235577 0.62105769 0.64677885]


In [ ]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))

Test Accuracy: 0.9004667005817169
Confusion Matrix for Decision Tree:
[[38877  1045]
 [ 3455  1834]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          no       0.92      0.97      0.95     39922
         yes       0.64      0.35      0.45      5289

    accuracy                           0.90     45211
   macro avg       0.78      0.66      0.70     45211
weighted avg       0.89      0.90      0.89     45211

